name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@master
    - name: DEBUG SSH
        uses: mxschmitt/action-tmate@v1
    - name: Install dependencies
      run: composer install