name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: check files 1
      run: |
        ls -l
    - uses: php-actions/composer@v1
    - name: check files 2
      run: |
        ls -l
      
    - name: Upload build for test runner
      uses: actions/upload-artifact@v1
      with:
        name: build-artifact
        path: ./

  test:
    runs-on: [ubuntu-latest]
    needs: [build]
    
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build-artifact
          path: ./

      - uses: php-actions/phpunit@v1
